name: Go

on:
  push:
    branches: [ "flatcar-master" ]
  pull_request:
    branches: [ "flatcar-master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: ./build

    - name: Test
      run: ./test
